### ISSUE TITLE
Describe high-level strategy and goals of this project.

### ISSUE THREAD

**Issue by bwklein** [thegooddocsproject/doctools-easy-button#8]
Reconsidering the purpose of this group, it seems that this project should provide a foundation and landing place for a collection of projects/repos that provide the same fundamental starting point for a new documentation site/service, but within different tech stacks.

Originally, this project would include a Hugo based site template, but I think this should be a separate project that is guided by and referenced to from this project.

This issue is to provide a starting point to updating the readme to describe the purpose and requirements of this project to allow for external projects to be included/referenced within it.

**Comment by zivbk1** [comment]
Consider defining how content reuse will work as a characteristic of a stack/system.

**Comment by zivbk1** [comment]
Make this the 'README' of the project.

**Comment by bwklein** [comment]
closed in #11
